# Import required components from LangGraph
from langgraph.graph import StateGraph, START, END

# TypedDict is used to define the structure of our graph state
# Literal restricts a value to specific possible strings
# Annotated allows us to define how state values should be updated
from typing import TypedDict, Literal, Annotated

# LangChain OpenAI chat model
from langchain_openai import ChatOpenAI

# Message types used for prompting the LLM
from langchain_core.messages import SystemMessage, HumanMessage

# operator.add will be used by LangGraph to append items to lists
import operator

# Loads environment variables from .env file
from dotenv import load_dotenv

# Pydantic is used to define the structured output schema
from pydantic import BaseModel, Field


# ---------------------------------------------------------
# ENVIRONMENT SETUP
# ---------------------------------------------------------

# Load variables from .env
# Example:
# OPENAI_API_KEY=your_api_key
load_dotenv()


# ---------------------------------------------------------
# CREATE LLMs
# ---------------------------------------------------------

# LLM responsible for generating the initial Facebook post
generator_llm = ChatOpenAI(model='gpt-4o-mini')

# LLM responsible for evaluating the generated post
evaluator_llm = ChatOpenAI(model='gpt-4o-mini')

# LLM responsible for improving the post based on feedback
optimizer_llm = ChatOpenAI(model='gpt-4o-mini')


# ---------------------------------------------------------
# STRUCTURED OUTPUT SCHEMA
# ---------------------------------------------------------

# This defines exactly what we expect from the evaluator LLM.
#
# evaluation can only be:
#   "approved"
#   "needs_improvement"
#
# feedback contains the evaluator's explanation.
class PostEvaluation(BaseModel):

    evaluation: Literal[
        "approved",
        "needs_improvement"
    ] = Field(
        ...,
        description="Final evaluation result."
    )

    feedback: str = Field(
        ...,
        description="Feedback for the Facebook post."
    )


# Convert the evaluator LLM into a structured-output LLM.
#
# Instead of returning normal text, the LLM will return
# something matching the PostEvaluation schema.
structured_evaluator_llm = evaluator_llm.with_structured_output(
    PostEvaluation
)


# ---------------------------------------------------------
# STATE DEFINITION
# ---------------------------------------------------------

# PostState represents the shared state of our LangGraph.
#
# Every node receives this state and can return updates to it.
class PostState(TypedDict):

    # Topic on which the post should be created
    topic: str

    # Current version of the Facebook post
    post: str

    # Evaluation result
    evaluation: Literal[
        "approved",
        "needs_improvement"
    ]

    # Feedback generated by evaluator
    feedback: str

    # Current optimization iteration
    iteration: int

    # Maximum number of iterations allowed
    max_iteration: int

    # Stores all generated versions of the post.
    #
    # operator.add tells LangGraph to APPEND new values
    # instead of replacing the existing list.
    post_history: Annotated[
        list[str],
        operator.add
    ]

    # Stores feedback from every evaluation.
    feedback_history: Annotated[
        list[str],
        operator.add
    ]


# ---------------------------------------------------------
# NODE 1: GENERATE POST
# ---------------------------------------------------------

def generate_post(state: PostState):

    # Create the prompt for the generator LLM
    messages = [

        # System message defines the personality/role
        SystemMessage(
            content="You are a funny and clever Facebook influencer."
        ),

        # Human message contains the actual task
        HumanMessage(
            content=f"""
Write a short, original, and hilarious Facebook post
on the topic: "{state['topic']}".

Rules:
- Do NOT use question-answer format.
- Max 500 characters.
- Use observational humor, irony, sarcasm, or cultural references.
- Think in meme logic, punchlines, or relatable takes.
- Use simple, day to day English.
"""
        )
    ]

    # Send the prompt to the generator LLM
    response = generator_llm.invoke(messages).content

    # Return the generated post.
    #
    # post_history receives the new post as a list.
    # Because post_history uses operator.add,
    # LangGraph will append this to the existing history.
    return {
        'post': response,
        'post_history': [response]
    }


# ---------------------------------------------------------
# NODE 2: EVALUATE POST
# ---------------------------------------------------------

def evaluate_post(state: PostState):

    # Create evaluation prompt
    messages = [

        # Tell the evaluator what role it should play
        SystemMessage(
            content="""
You are a ruthless, no-laugh-given Facebook critic.
You evaluate posts based on humor, originality,
virality, and post format.
"""
        ),

        # Give the evaluator the current post and evaluation rules
        HumanMessage(
            content=f"""
Evaluate the following Facebook post:

Post: "{state['post']}"

Use the criteria below to evaluate the post:

1. Originality – Is this fresh, or have you seen it
   a hundred times before?

2. Humor – Did it genuinely make you smile, laugh,
   or chuckle?

3. Punchiness – Is it short, sharp, and
   scroll-stopping?

4. Virality Potential – Would people share,
   react, or comment on it?

5. Format – Is it a well-formed Facebook post
   (not a setup-punchline joke, not a Q&A joke,
   and under 500 characters)?

Auto-reject if:

- It's written in question-answer format
  (e.g., "Why did..." or "What happens when...")

- It exceeds 500 characters

- It reads like a traditional setup-punchline joke

- Don't end with generic, throwaway, or deflating
  lines that weaken the humor.

Respond ONLY in structured format:

- evaluation: "approved" or "needs_improvement"
- feedback: One paragraph explaining the strengths
  and weaknesses.
"""
        )
    ]

    # Ask the structured-output LLM to evaluate the post
    response = structured_evaluator_llm.invoke(messages)

    # Return evaluation results to the graph state
    return {
        'evaluation': response.evaluation,
        'feedback': response.feedback,

        # Save this feedback in the feedback history
        'feedback_history': [response.feedback]
    }


# ---------------------------------------------------------
# NODE 3: OPTIMIZE POST
# ---------------------------------------------------------

def optimize_post(state: PostState):

    # Create prompt for the optimizer
    messages = [

        # Define the optimizer's role
        SystemMessage(
            content="""
You punch up Facebook posts for virality and humor
based on given feedback.
"""
        ),

        # Provide the evaluator feedback and current post
        HumanMessage(
            content=f"""
Improve the Facebook post based on this feedback:

"{state['feedback']}"

Topic: "{state['topic']}"

Original Post:
{state['post']}

Re-write it as a short, viral-worthy Facebook post.

Avoid Q&A style and stay under 500 characters.
"""
        )
    ]

    # Generate an improved version of the post
    response = optimizer_llm.invoke(messages).content

    # Increase the iteration count
    iteration = state['iteration'] + 1

    # Return the improved post and updated iteration
    return {
        'post': response,
        'iteration': iteration,

        # Store the improved post in history
        'post_history': [response]
    }


# ---------------------------------------------------------
# ROUTER / CONDITIONAL EDGE
# ---------------------------------------------------------

def route_evaluation(state: PostState):

    # If the evaluator approved the post,
    # stop the workflow.
    #
    # Also stop if maximum iterations have been reached.
    if (
        state['evaluation'] == 'approved'
        or state['iteration'] >= state['max_iteration']
    ):
        return 'approved'

    # Otherwise, send the post to the optimizer
    return 'needs_improvement'


# ---------------------------------------------------------
# CREATE LANGGRAPH STATE GRAPH
# ---------------------------------------------------------

# Create a StateGraph using our PostState definition
graph = StateGraph(PostState)


# ---------------------------------------------------------
# ADD NODES
# ---------------------------------------------------------

# Node responsible for generating the first post
graph.add_node(
    'generate',
    generate_post
)

# Node responsible for evaluating the post
graph.add_node(
    'evaluate',
    evaluate_post
)

# Node responsible for improving the post
graph.add_node(
    'optimize',
    optimize_post
)


# ---------------------------------------------------------
# ADD EDGES
# ---------------------------------------------------------

# Workflow starts by generating a post
graph.add_edge(
    START,
    'generate'
)

# After generation, evaluate the post
graph.add_edge(
    'generate',
    'evaluate'
)

# After evaluation, use the router to decide
# whether to finish or optimize the post.
#
# If route_evaluation returns:
#
# "approved"
#       -> END
#
# "needs_improvement"
#       -> optimize
graph.add_conditional_edges(
    'evaluate',
    route_evaluation,
    {
        'approved': END,
        'needs_improvement': 'optimize'
    }
)

# After optimization, evaluate the new post again.
#
# This creates the feedback loop:
#
# generate
#    ↓
# evaluate
#    ↓
# optimize
#    ↓
# evaluate
#    ↓
# optimize
#    ↓
# ...
graph.add_edge(
    'optimize',
    'evaluate'
)


# ---------------------------------------------------------
# COMPILE THE GRAPH
# ---------------------------------------------------------

# Compile the StateGraph into an executable workflow
workflow = graph.compile()


# ---------------------------------------------------------
# INITIAL STATE
# ---------------------------------------------------------

# This is the initial data provided to the graph.
initial_state = {
    "topic": "agentic AI",

    # Start from iteration 1
    "iteration": 1,

    # The graph can optimize the post at most 5 iterations
    "max_iteration": 5
}


# ---------------------------------------------------------
# RUN THE WORKFLOW
# ---------------------------------------------------------

# Execute the LangGraph workflow
result = workflow.invoke(initial_state)


# ---------------------------------------------------------
# RESULT
# ---------------------------------------------------------

# The final state contains:
#
# result["post"]             -> final post
# result["evaluation"]       -> approved / needs_improvement
# result["feedback"]         -> latest feedback
# result["iteration"]        -> number of iterations
# result["post_history"]     -> all generated versions
# result["feedback_history"] -> all evaluator feedback